name: ci

on: push

jobs: 
  ci: 
    runs-on: ubuntu-latest 
    steps: 
      - name: checkout repo
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install 
      - name: Run tests 
        run: npm test 
        
  cd:
    runs-on: ubuntu-latest
    needs: ci
    if: github.ref == 'refs/head/main'
    steps:
        - uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.SSH_HOST }}
            username: ${{ secrets.SSH_USER }}
            password: ${{ secrets.SSH_PASSWORDS }}
            port: ${{ secrets.SSH_PORT }}
            script: |
              cd ~/se2/33/se2-example-backend
              git reset --hard origin/main 
              git pull https://${{ secrets.CLONE_TOKEN }}@github.com/eegrigor/se2-example-backend main
              bash -ci 'npm install'
              bash -ci 'pm2 restart example-backend-33'
